redhat-exd-rebuilds/freshmaker

- Dockerfile
- Jenkinsfile
After this change, the Jenkins pipeline job defined by Jenkinsfile
will only be responsible for building docker container images and
tagging images with git commit short SHA.
If job is ran for master branch, images will be tagged as latest.
> Update Jenkinsfile to build docker container image

- docs/db.rst
- docs/index.rst
> Add database section to documentaion

- freshmaker/events.py
Add freshmaker_event_id in the ErrataBaseEvent class.
> Add freshmaker_event_id

- README.md
- requirements.txt
- scripts/print_handlers_md.py
- tests/helpers.py
- yum-packages.txt
PDC is not used in Freshmaker anymore.
resolve: #15
> Remove PDC references

- freshmaker/handlers/koji/rebuild_images_on_async_manual_build.py
ref: CLOUDWF-2810
Signed-off-by: Giulia Naponiello <gnaponie@redhat.com>
> Fix a typo: parent image is a tuple instead of None

- freshmaker/handlers/koji/rebuild_images_on_async_manual_build.py
- tests/handlers/koji/test_rebuild_images_on_async_manual_build.py
Previously we were using wrong key for retrieving parent image nvr for
async rebuilds.
RESOLVES: CLOUDWF-2810
> Set parent build to the right value

- README.md
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
> Link to the Freshmaker docs from README.md

- contrib/freshmaker-cli
Check if the RHSA in SHIPPED state  were catched by freshmaker.
JIRA: https://projects.engineering.redhat.com/browse/CLOUDWF-555
> Check advisories missed by freshmaker

- freshmaker/handlers/koji/rebuild_images_on_async_manual_build.py
- freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
- tests/test_lightblue.py
Change the  name of the stored event id in LightBlue class.
JIRA:https://projects.engineering.redhat.com/browse/CLOUDWF-3731
> Change the saved name of the stored event id

- conf/config.py
- dev_scripts/config.py.template
- docs/api_v1.rst
- freshmaker/config.py
- freshmaker/events.py
- freshmaker/handlers/__init__.py
- tests/handlers/bob/test_rebuild_images_on_image_advisory_change.py
- tests/handlers/botas/test_botas_shipped_advisory.py
- tests/handlers/internal/test_generate_advisory_signed_event_on_rpm_sign.py
- tests/handlers/internal/test_update_db_on_advisory_change.py
- tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
- tests/test_handler.py
Signed-off-by: Giulia Naponiello <gnaponie@redhat.com>
> Rename black/white lists to be more inclusive

- freshmaker/pyxis.py
- tests/test_pyxis.py
@apaplaus PTAL
For now it's just a WIP since I have to fix the tests yet - had a bit of a problem to run them since I don't have rpm based distro.
> `get_latest_bundle` now uses `latest_in_channel` field

- freshmaker/handlers/__init__.py
- tests/test_handler.py
Now Freshmaker will continue building images even when some exception is
raised during one of the builds. Previously other builds were skipped
and build event was stuck in 'BUILDING' state.
JIRA: CWFHEALTH-35
> Freshmaker continue building images after exception

- freshmaker/errata.py
- freshmaker/handlers/botas/botas_shipped_advisory.py
- tests/handlers/botas/test_botas_shipped_advisory.py
- tests/test_errata.py
Freshmaker while handling advisory with operator bundle will check not
only for original images, but also for images from blocking/previous
advisories and mark them for rebuild too. Because sometimes previously
rebuilt bundle image could have overriten original NVR of the
operator/operand images, so it might not be marked for rebuild event if
it should be.
JIRA: CWFHEALTH-60
> Check blocking advisories for overlapping images

- docs/configuration.rst
> Add documentation about EUS images

- freshmaker/parsers/errata/state_change.py
When an ErrataAdvisoryStateChangedEvent is generated from an advisory
state change message, override the advisory state with new state in
message. This is because when there is message delay, a message of
advisory state change to other states (QE, REL_PREP, PUSH_READY) can 
arrived after an advisory has already been shipped, and rebuilds can 
be triggered for multiple times.
For example, there is an advisory 101, and its state was changed as
following:
1. 10:10:58: NEW_FILES -> QE, message A sent
2. 10:39:52: QE -> REL_PREP, message B sent
3. 10:45:07: REL_PREP -> PUSH_READY, message C sent
4. 10:46:22: PUSH_READY -> IN_PUSH, message D sent
5. 11:15:11: IN_PUSH -> SHIPPED_LIVE, message E sent
But there is something wrong on messaging, Freshmaker received the 
first message A at 12:38:02, …
> Override advisory state with state in state change message

- freshmaker/handlers/botas/botas_shipped_advisory.py
- tests/handlers/botas/test_botas_shipped_advisory.py
See this document for why these changes are needed:
https://hackmd.io/@5VB9CW2uTva8DIRU7MMO2A/BkSw7dV8_
> Adjust the CSV modifications based on the release substitutesFor feature

- freshmaker/lightblue.py
- tests/test_lightblue.py
> Check extra image repo before start

- freshmaker/config.py
- freshmaker/pyxis.py
- tests/test_pyxis.py
Modify get_operator_indices method for searching index images for
multiple organizations.
> Search index images for multiple organizations

- freshmaker/handlers/botas/botas_shipped_advisory.py
- freshmaker/pyxis.py
This will help debug any issues that come up.
> Add additional log messages in the BOTAS Advisory handler

- freshmaker/config.py
- freshmaker/handlers/botas/botas_shipped_advisory.py
- tests/handlers/botas/test_botas_shipped_advisory.py
This will be used for E2E testing.
> Add an exception for bundle images not tagged with auto-rebuild tags

- freshmaker/handlers/botas/botas_shipped_advisory.py
This was missed as part of f305de0.
> Add support for semver 2.8.1

- freshmaker/handlers/botas/botas_shipped_advisory.py
- freshmaker/views.py
- tests/handlers/botas/test_botas_shipped_advisory.py
- tests/test_views.py
This is the expected property name by OSBS:
https://github.com/containerbuildsystem/atomic-reactor/blob/547f3edd28628dc59a98c4928a0ecf280f5983cb/atomic_reactor/schemas/operator_csv_modifications.json#L8-L12
> Use pullspec_replacements instead of pullspecs in the CSV modifications

- freshmaker/handlers/botas/botas_shipped_advisory.py
- freshmaker/pyxis.py
- tests/handlers/botas/test_botas_shipped_advisory.py
- tests/test_pyxis.py
Switch from version field to version_original for operator bundles.
> Change version to version_original

- tests/test_lightblue.py
Add patches to unittests.
https://issues.redhat.com/browse/CWFHEALTH-690
> Fix unmocked unittests

- freshmaker/views.py
- tests/test_views.py
Check if there is already another event running for the same advisory.
> Disallow multiple events

- freshmaker/lightblue.py
- tests/test_lightblue.py
> Set isolated only for flatpak builds

- freshmaker/config.py
- freshmaker/errata.py
- freshmaker/events.py
- freshmaker/models.py
- freshmaker/parsers/errata/__init__.py
- freshmaker/parsers/errata/signing_change.py
- freshmaker/parsers/errata/state_change.py
- tests/test_flatpaks.py
> Add event to rebuild Flatpak applications

- freshmaker/kojiservice.py
- tests/test_kojiservice.py
Add a new API in kojiservice to get CSV data of bundle image from
koji/brew service.
JIRA: CWFHEALTH-913
> Add api to get bundle CSV data from koji/brew

- freshmaker/errata.py
- tests/test_errata.py
> Add method to get module builds nvr in advisory

- freshmaker/lightblue.py
- tests/test_lightblue.py
> Upgrade the base images to the latest released when the base image is unreleased

- freshmaker/errata.py
- tests/test_errata.py
New "with_sig_key" GET parameter was added to Errata Tool API in
RHELWF-4641. With this we can list all attached builds with "is_signed"
property:
/api/v1/erratum/{id}/builds_list?with_sig_key=1
> Get signed state for builds from updated ET API

- fedmsg.d/freshmaker-logging.py
- yum-packages.txt
Make JSON logger to write structured data to a file.
(JIRA: CWFHEALTH-778)
> JSON logging into file

- requirements.in
- requirements.txt
- yum-packages.txt
Json logging added python-json-logger to requirements
> JSON logging new

- freshmaker/lightblue.py
- tests/test_handler.py
- tests/test_lightblue.py
> Make flatpak rebuilds always isolated

- freshmaker/config.py
- freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
- tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py
> Filter out rebuild image candidates in handle method

- freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
- freshmaker/kojiservice.py
- freshmaker/lightblue.py
- tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py
- tests/test_kojiservice.py
- tests/test_lightblue.py
Add new method to resolve odcs compose id for flatpak
image.
Add logic to filter out compose in sets renew and new.
Link composes to build and record builds in database.
JIRA: RHELWF-3780
> Resolve and record builds in database

- freshmaker/events.py
- freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
- freshmaker/models.py
- freshmaker/parsers/internal/manual_rebuild.py
- tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py
> Support manual rebuild of Flatkpak app images

- freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
- tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py
Fix some issues when submitting a real flatpak build.
1. Arches should be inherited from image when creating composes.
2. Emptyp list for rpm_nvrs will cause LightBlueSystemError, input
None instead.
3. Add build arg original_parent as None as discussed in RHELWF-3779.
It is a required arg when build image.
JIRA: RHELWF-3861
> Submit flatpak build task

- freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
The return value should be list of unhandled events.
JIRA: RHELWF-5907
> Fix returning invalid value from module handler

- freshmaker/pyxis_gql.py
- requirements.in
- requirements.txt
- test-requirements.txt
- tests/fixtures/pyxis.graphql
- tests/test_pyxis_gql.py
A basic Pyxis GraphQL module to provide APIs for Pyxis queries with
Domain Specific Language.
JIRA: CWFHEALTH-1247
> Add basic Pyxis GraphQL module

- freshmaker/config.py
Refactor and simplify freshmaker configuration files and set up
Jira: CWFHEALTH-1159
> Freshmaker configuration refactoring

- freshmaker/logger.py
Change getting env vars for logging.
JIRA: CWFHEALTH-1456
> Fix logging

- freshmaker/container.py
- freshmaker/pyxis_gql.py
- tests/test_container.py
- tests/test_pyxis_gql.py
Use Pyxis GraphQL to find images that have specified rpms installed, and the installed NVRs are older than specified NVRs.
JIRA: CWFHEALTH-1249
> Add APIs to find images have older rpms installed

- freshmaker/container.py
- freshmaker/kojiservice.py
- freshmaker/pyxis_gql.py
- tests/test_container.py
- tests/test_pyxis_gql.py
Resolve container to populate additional metadata (build metadata and compose sources) by querying Pyxis and Koji.
JIRA: CWFHEALTH-1250
> Resolve container to populate build metadata and compose sources

- freshmaker/pyxis_gql.py
- tests/test_pyxis_gql.py
Implement find_images_by_names with Pyxis GraphQL with same projection as LightBlue's result, Jira: CWFHEALTH-1251
> Implement find_images_by_names with Pyxis GraphQL

- freshmaker/lightblue.py
Check if parent_build_id exists and if not, FM skip it.
JIRA: CWFHEALTH-1628
> Check availability parent_build_id

- freshmaker/lightblue.py
- freshmaker/pyxis_gql.py
- tests/test_lightblue.py
- tests/test_pyxis_gql.py
> [switch-to-pyxis] get_fixed_published_image with Pyxis APIs

- freshmaker/errata.py
- tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py
> Rebuild for Zstream Flatpak module errata

- freshmaker/image.py
- tests/test_image.py
GQL's sync transport (`RequestsHTTPTransport`) can't be shared among threads, create one PyxisGQL instance per thread to run Pyxis queries in parallel.
JIRA: CWFHEALTH-1352
> Create one PyxisGQL instance per thread

- freshmaker/pyxis_gql.py
Due to ISV-3642, in some cases, Pyxis is not able to return result when a query in API find_images_by_name_version is submitted, we need to limit the number of images in such queries to workaround the issue.
JIRA: CWFHEALTH-2047
> Limit number of result while querying for images match name and version

- freshmaker/pyxis.py
- freshmaker/pyxis_gql.py
- freshmaker/pyxis_gql_async.py
- tests/test_pyxis.py
- tests/test_pyxis_gql.py
- tests/test_pyxis_gql_async.py
In case of an error with a request to Pyxis, it is useful to log the `trace_id` property for later debugging. This property is stored in the response headers from pyxis. This commit fetches its value and stores it in the logging apparatus.
This commit includes the following changes:
- fetching the `trace_id` relative to the Pyxis query in case of an error, in the three Pyxis modules (`pyxis.py`, `pyxis_gql.py` and `pyxis_gql_async.py)
- new error classes with more structure in the gql modules (`pyxis_gql.py` and `pyxis_gql_async.py)
- refactoring of the error checks in the gql modules, which are now centralized to the query methods; this should avoid unnecessary duplication
- unit tests for the fetching and storing of trace id in the three Pyxis modules
- a few linting and formatting …
> feat: Log trace_id in case of Pyxis request error

- freshmaker/pyxis_gql.py
- freshmaker/pyxis_gql_async.py
Reordering the filters from most specific to least specific can improve the performance of queries in Pyxis.
> Reorder the Pyxis query filters

- freshmaker/handlers/botas/botas_shipped_advisory.py
- tests/handlers/botas/test_botas_shipped_advisory.py
We previously added a feature to automatically include previous rebuilds in the NVR mapping during a bundle rebuild.
However, our implementation was missing the most original NVR, as it was not an NVR rebuild itself.
This commit makes a slight change so that the most original NVR is also included.
JIRA: CWFHEALTH-2264
I adjusted the unit test to fit this case. Also, I made a deployment to the dev environment with the initial messages and they were processed fine. I left the pod running for about a day and the prod-consumer pod did not have any error as well.
> Include most original NVR in bundle rebuilds

- .github/workflows/docs.yml
- freshmaker/events.py
- tests/handlers/koji/test_rebuild_images_on_async_manual_build.py
1. Fix doc build error in Github action
2. Fix unit test failures
> Fix Github action and test failures

- freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
- tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
This commit changes our approach to handling moderate security advisories by removing the restriction that previously limited rebuilds to only compliance priority repositories. Now, all repositories are eligible for rebuilds when a moderate security advisory is released.
JIRA: CWFHEALTH-2876
> Allow rebuilds for all repos on moderate security advisories

- freshmaker/kojiservice.py
- freshmaker/pyxis.py
- freshmaker/pyxis_gql.py
Updated dogpile configuration where expiration time was previously missing.
> Add missing expiration time to dogpile caching

- freshmaker/config.py
- freshmaker/errata.py
- requirements.in
- requirements.txt
- tests/test_errata.py
- yum-packages.txt
Check advisory for JIRA issues that have:
1. Vulnerability type
2. "contract-priority" value in special handling field
JIRA: CWFHEALTH-2892
> Check contract-priority Jira vulnerability issue in advisory
