redhat-exd-rebuilds/freshmaker

Dockerfile
yum-packages.txt

1. Tested latest qpid-proton doesn't have the memory leak issue, so we don't need the old version of qpid-proton packages.
2. Tested with some messages locally, handlers can run without issue.

Update container image to Fedora 32

---

Jenkinsfile

When use the same tag, the latter image will overrides previously built
image, and the latter one will be pushed to both internal and quay.io
registry.

Use different tags for internal docker image and quay.io image

---

requirements.txt
tests/test_views.py

Flask v1.0.3 fixed this bug https://github.com/pallets/flask/issues/2984.
So we just need to specify required version of Flask to be installed +
some tests.
Resolves: FACTORY-5859

Add version requirements for Flask to deal with redirections problem

---

dev_scripts/README.md
dev_scripts/find_images_to_rebuild.py

Modify the "find_images_to_rebuild.py" script to be able to use a
cassette downloaded from the Freshmaker production instance rather
than querying Lightblue directly.

 Modify script to load a cassette

---

freshmaker/lightblue.py
tests/test_lightblue.py

The comment in _deduplicate_images_to_rebuild says:
the current implementation is updating the parent when parent is
changed from x-1-1 to y-1-1, where the name is changed, so why not
also update parent when only version changes?
With this change, if we have a case of:
- foo-1-1 was built against x-1-1
- foo-1-2 was built against x-2-1
then in additional to replace "foo-1-1" by "foo-1-2", we update parent
image to "x-2-1" as well.

Update parent image when parent image's version changes

---

conf/config.py
freshmaker/config.py
setup.py
tests/test_handler.py

Some fedora references are left because it could be useful in future for OIDC authentication.
RESOLVE: CLOUDWF-2666

[WIP]Remove some old references of pagure and fedoraproject

---

Dockerfile

Install find in the Freshmaker container for the possibility to create
an OpenShift CronJob to delete cassettes on the persistent volume that
are older than two weeks.
JIRA: https://projects.engineering.redhat.com/browse/CLOUDWF-1937

Adding the findutils install in the Dockerfile

---

freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py

Fixed a regression in 3726cd4, after changing to use CVE mapping
feature from errata, the case of non-CVE advisory triggered rebuilds
will not work, this is a case in E2E testing. Put the code back to
fix it.

Filter images by builds in advisory for non-CVE advisories

---

freshmaker/config.py
freshmaker/lightblue.py
tests/test_lightblue.py

Images from build repositories should not be include in our rebuild
list, to filter out these images, we have a new configurable
"IMAGE_BUILD_REPOSITORY_REGISTRIES" which can be set in config.py,
it's a list of build repository registries. If an image's repository
registry is in this list, the image will be excluded.
JIRA: CLOUDWF-3094

Exclude images from build repositories

---

dev_scripts/template_errata.py
freshmaker/errata.py
freshmaker/handlers/koji/rebuild_images_on_parent_image_build.py
freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
freshmaker/image_verifier.py
freshmaker/lightblue.py
freshmaker/odcsclient.py
tests/handlers/koji/test_rebuild_images_on_parent_image_build.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
tests/test_errata.py
tests/test_image_verifier.py
tests/test_lightblue.py
tests/test_odcsclient.py

Now we will use binary rpms instead of SRPMs to filter images. It's
possible due to new functionality in ET, allowing us to get binary rpms
affected by CVEs in an advisory straight from ET.
RESOLVE CLOUDWF-2968

Use binary rpms for filtering images

---

freshmaker/image_verifier.py
freshmaker/lightblue.py
freshmaker/views.py
tests/test_image_verifier.py
tests/test_views.py

When image repository doesn't have auto_rebuild_tags set, the return
message of verify-image-repository API tells user the repository doesn't
exist, like this:
{
"error": "Bad Request",
"message": "Cannot get repository foo/bar from Lightblue.",
"status": 400
}
Instead of this message, freshmaker should tells users that this
repository doesn't have auto_rebuild_tags set. After change, the return
message will be something like:
{
"error": "Bad Request",
"message": "The \"auto_rebuild_tags\" in COMET is not set.",
"status": 400
}
In this change, the return message is changed to include more info about
the repository and the rebuildable images, including the 'auto_rebuilds_tags'
for repository and tags of image. Something like this:
{
"auto_rebuild_tags": [
"latest"
],
"images": { …

Improve return messages for verify-image-repository API

---

freshmaker/image_verifier.py

Some repos may not have release_categories, fix KeyError for such repos.

Fix KeyError when repo has no release_categories

---

.dockerignore
Dockerfile

Now we will use publicly available copr repo for python-rhmsg, because we
need it to use quay.io build. So now we can build Freshmaker image on
quay.io. And so we don't have any internal packages dependencies.
And for now we don't have solution on how to create lable with git commit hash, so I removed that functionality for now. Because Quay doesn't support build-arg for docker build.
RESOLVE: CLOUDWF-2607

Use publicly available copr repo for python-rhsm

---

freshmaker/lightblue.py
tests/test_lightblue.py

While querying images from LightBlue, Freshmaker has such a filter to
filter out images which don't have Dockerfile in dist-git repos:
{
"field": "parsed_data.files.*.key",
"op": "=",
"rvalue": "buildfile"
},
When an image has Dockerfile in its dist-git repo, the saved metadata in
LighBlue will include something like this:
"parsed_data": {
"files": [
{
"content_url": "http://dist-git.example.com/testimage/plain/Dockerfile?id=242a0a1e38ca1c31db070b687f68e7e6afc05d43",
"filename": "Dockerfile",
"key": "buildfile"
},
],
...
}
For some images, they don't have Dockerfile in dist-git repo, but OSBS
can generate a Dockerfile based on the information in container.yaml, to
include these images in our rebuild list, in this commit, we removed the
query criteria of "buildfile" in parsed_data.files. …

Include images without Dockerfile in dist-git repo

---

freshmaker/config.py
freshmaker/lightblue.py
tests/test_lightblue.py

Add 'vendor' parameter to Lightblue queries, so now we will get container images only with Red Hat vendor.
Resolves: CLOUDWF-3527

Query images from Lightblue only with RH vendor

---

README.md
dev_scripts/botas_advisory_test.py
freshmaker/errata.py
freshmaker/events.py
freshmaker/handlers/botas/__init__.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/models.py
freshmaker/parsers/errata/state_change.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_errata.py
tox.ini

Add new handler to handle advisories in SHIPPED_LIVE state
that were filed by BOTAS. We need that for future support of Operators CVE
rebuild functionality. To support rebuilding of Bundle images.
+ small badge to see container build status in Quay
RESOLVE: CLOUDWF-3611

Botas advisory handler

---

freshmaker/lightblue.py

A separate commit also clarifies the docstring of `ContainerImage.resolve`.
I find this syntax a little easier to read, but if you disagree, we can close this PR.

Make _deduplicate_images_to_rebuild syntactically more concise

---

freshmaker/lightblue.py
tests/test_lightblue.py

When Freshmaker has to rebuild parent images that are not directly affected, it now detects if it can use the latest released image at the pull specification declared by the child image. If it can, this parent image is used instead of rebuilding the original parent image.
Resolves CLOUDWF-541

Consider latest released images for "dependency" images

---

conf/config.py
dev_scripts/config.py.template
freshmaker/config.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/pyxis.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py

New Pyxis module to query bundle images and ContainerImages by thier
nvrs. So we can find bundle images for the operator/operand images that
were rebuilt by us previously.

Query bundles for the rebuilt operators/operands

---

freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/pyxis.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py

New Pyxis module to query bundle images and ContainerImages by thier
nvrs. So we can find bundle images for the operator/operand images that
were rebuilt by us previously.
Resolve CLOUDWF-3955

Auto rebuilt filter

---

freshmaker/config.py
freshmaker/pyxis.py
freshmaker/utils.py
test-requirements.txt
tests/test_pyxis.py

Operator index can exists in Pyxis even the product has not been
released, these indices should be excluded. By checking Product
Page, we can get release date of an OpenShift version, and then
can compare the release date with current date to know whether
the product is released.
JIRA: CLOUDWF-4084

Exclude operator indices that haven't been released

---

freshmaker/kojiservice.py
requirements.txt
yum-packages.txt

Use koji's gssapi_login API instead of krb_login
krb_login() is deprecated, and for ClientSession objects, krb_login()
is currently redirected to gssapi_login() with a printed warning.
More details:
https://docs.pagure.org/koji/migrations/migrating_to_1.22/#migration-krbv
And add python requests-kerberos package explicitly in yum-packages.txt
and requirements.txt.

Migrate to koji gssapi_login API

---

freshmaker/errata.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/pyxis.py
tests/handlers/botas/test_botas_shipped_advisory.py

Fix bug when original nvrs were extracted from new event instead of
searching for advisory builds and then searching Freshmaker db for older
build events.

Get original nvrs from incoming message

---

Dockerfile

Pulling fedora base image from docker registry can reach to pull rate
limit, and image build job will fail due to that, change base image to
fedora from quay.io.
Resolves: #48

Use fedora base image from quay.io

---

tox.ini

With new mypy 0.800 there are errors while checking against docs
directory, because mypy doesn't support excluding files/directories,
and since docs is not a module, we can't ignore the errors with:
[mypy.docs]
ignore_errors = True
In this change, we specify the directories to check explicitly to
workaround this.

Fix CI with mypy 0.800

---

freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/migrations/versions/fcba8824bf8d_add_bundle_pullspec_overrides.py
freshmaker/models.py
freshmaker/pyxis.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py

For each bundle image we're going to rebuild when operator/operand
images are shipped, pullspec overrides data is required, the general
workflow is: 
1. Get the current image NVRs in advisory, these are rebuilt images
2. Get the original image NVRs for rebuilt images
3. Get digests of original images
4. Get digests of rebuilt images
5. With digests of original images, we can search in all latest bundle
images to get the bundles which have original images are connected.
6. For each bundle image, if this image is not enabled for rebuild, skip
it.
7. For each bundle image, if a related image is in original digests (step
3), and osbs-pinning is used, update the digest with digest of rebuilt
image.
JIRA: CLOUDWF-2902

Add pullspec overrides data for related images in each bundle image

---

freshmaker/lightblue.py
tests/test_lightblue.py
tests/test_utils.py

Now EUS base image will be marked as directly affected, despite it's unpublished, so botas could
file an advisory.
RESOLVE: CWFHEALTH-24

Mark EUS base image as directly affected

---

freshmaker/handlers/botas/botas_shipped_advisory.py

This indicates that the pullspec was replaced by Freshmaker in
the bundle image.
This is a followup to #45.

Always set pinned to true when Freshmaker replaces a pullspec

---

conf/config.py
freshmaker/config.py
freshmaker/lightblue.py
tests/test_lightblue.py
tests/test_utils.py

Reverting commit that make EUS images marked as **directly_affected** + modify Lightblue module to query unpublished repositories specified in configuration file.

Eus images support

---

freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py

Now content_sets list will consist of pulp
repository ids and content sets assiciated with those repositories
JIRA: CWFHEALTH-22

Add repo ids to content sets

---

freshmaker/lightblue.py

Its usage was removed in e03b3699bf8dce0ac1bfd8849fa3dd33425044f2.

Remove the unused ContainerImage.dockerfile property method

---

freshmaker/lightblue.py
tests/test_lightblue.py

Unpublished exceptions for images such as EUS only matter at the
repository level. The repositories[].published value on a containerImage
entity is different according to Release Engineers.
This is based on the following statement from a Release Engineer:
>  I think that there is a published flag at the image level,
which is true to indicate that the image is published in the repo.
And there is another flag at the repo level to indicate whether the
repo is visible in RHEC.

Make unpublished_exceptions only apply to container repos

---

freshmaker/handlers/internal/update_db_on_odcs_compose_fail.py
freshmaker/handlers/koji/rebuild_images_on_odcs_compose_done.py

When see a message of ODCS compose state change, logging it so we can
check logs to know whether Freshmaker saw this message. And only logging
when this ODCS compose is connected with some builds.

Logging ODCS compose state change

---

freshmaker/views.py
tests/test_views.py

Add API endpoint to get pullsecs overrides for bundle images builds

Add new API endpoint for pullspecs overrides

---

freshmaker/image_verifier.py
tests/test_image_verifier.py

The first two commits fix the unit tests.

Add support for unpublished exceptions on the verify-image API endpoint

---

conf/config.py
freshmaker/config.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/lightblue.py
tests/handlers/botas/test_botas_shipped_advisory.py

Since we already know digests of bundle images that should be rebuilt,
now build objects are created for every image and submitted to OSBS.
Besides the other common information about build, pullspec overrides url is
submitted to OSBS.
JIRA: CWFHEALTH-104

Submit bundle builds to OSBS

---

freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/pyxis.py
requirements.txt
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py
yum-packages.txt

When Freshmaker rebuilds bundle images, it must modify some attributes in the ClusterServiceVersion (CSV) file of the bundle
image so that it is added to the upgrade graph appropriately in an index image.
Resolves CWFHEALTH-76

Determine the CSV modifications to send to the build system

---

freshmaker/events.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/models.py
freshmaker/parsers/internal/manual_rebuild.py
freshmaker/pyxis.py
freshmaker/views.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py
tests/test_views.py

Release driver will send manual request for bundle rebuild to Freshmaker
in format:
{
"container_images": ["app-bundle-1.0-1.22222"],
"bundle_images": ["app-bundle-1.0-1.11111"],
"metadata": release_driver_metadata,
}
Freshmaker will check pullspecs overrides of 'bundle_images'(the
original overwritten values) and if some of them are the same as the
current pullspec overrides in 'container_images' bundles. Then those
bundles(from 'container_images') will be rebuilt with the new pullspec overrides.
JIRA: CWFHEALTH-332

Add manual bundle rebuild functionality

---

freshmaker/pyxis.py
tests/test_pyxis.py

change
f'latest_in_channel==true%20and%20source_index_container_path=={path}'
to
f'latest_in_channel==true and source_index_container_path=={path}'
requests.get will encode the params, no necessary to encode it before
sending the request, and it will result in bad request.

Fix Pyxis filter request param in get_latest_bundles

---

Dockerfile

This will allow logging to be configured in /etc/fedmsg.d.

Delete the default fedmsg logging configuration in the container

---

freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/pyxis.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py

The issue is that there is a delay from when a BOTAS advisory
is shipped and when Pyxis is updated with the published
repositories entry on the image. The manifest list digest
is the same in both cases, so it's safe to fallback to the
unpublished manifest list digest value for this case.

Allow manifest list digests from unpublished repositories

---

freshmaker/handlers/botas/botas_shipped_advisory.py
tests/handlers/botas/test_botas_shipped_advisory.py

The build system always enforces that bundle images build from
"scratch", so there is no parent image. See:
https://osbs.readthedocs.io/en/latest/users.html?#operator-manifest-bundle-builds

Specify a null original parent for bundle image rebuilds

---

freshmaker/handlers/botas/botas_shipped_advisory.py
tests/handlers/botas/test_botas_shipped_advisory.py
tox.ini

There is a character limit of 63 characters for the
ClusterServiceVersion (CSV) name due to how they are used in Kubernetes
under the hood. This shortens the build ID suffix and thus shortens
the CSV name a little bit to meet the large majority bundle images.

Shorten the CSV version build ID suffix

---

freshmaker/handlers/botas/botas_shipped_advisory.py
tests/handlers/botas/test_botas_shipped_advisory.py

Adding the build ID to the CSV name makes the CSV name
not compliant with DNS names, which is required by Kubernetes:
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
@gallettilance suggested replacing the "+" due to the build ID with a ".".

Make the CSV names DNS name compliant

---

freshmaker/handlers/botas/botas_shipped_advisory.py

This also skips missing bundle digests for manual bundle rebuilds to avoid an IndexError.

Add logging for manual bundle rebuilds

---

freshmaker/handlers/botas/botas_shipped_advisory.py
tests/handlers/botas/test_botas_shipped_advisory.py

This was previously set to the version which is incorrect.

Set olm.substitutesFor to the CSV name

---

freshmaker/config.py
freshmaker/events.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/parsers/internal/manual_rebuild.py
freshmaker/views.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_views.py

Now when there is need in retriggering bundle build due to fail or
something else, there is functionality for it.
Note: it's implemented only to retrigger automatic rebuilds, it's not
for manual rebuild event triggered by BOTAS.
JIRA: CWFHEALTH-603

Add manual retriggering of bundle rebuild

---

docs/api_v1.rst
freshmaker/models.py

For container images, `build_id` is actually the build task id,
the name is easy to make some confusions, update doc and comment
for this.
See #99

Update comment and doc for `build_id`

---

docs/api_v1.rst
freshmaker/models.py

Explain that the Koji task that we track in `build_id` is a buildContainer task.
Publicly document that a null `build_id` implies that Freshmaker did not submit the task *or* that Koji did not give a task ID back to Freshmaker.

further updates to build_id docs

---

freshmaker/events.py
freshmaker/parsers/internal/manual_rebuild.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_views.py

1. return advisory id as search_key of manual bundle rebuild when it exists
2. store requester_metadata_json data in database

Fix bundle manual rebuild

---

contrib/freshmaker-cli
contrib/generate_report.py
contrib/get_freshmaker_stats.py
freshmaker/auth.py
freshmaker/config.py
freshmaker/errata.py
freshmaker/handlers/bob/rebuild_images_on_image_advisory_change.py
freshmaker/kojiservice.py
freshmaker/lightblue.py
freshmaker/pulp.py
tests/handlers/bob/test_rebuild_images_on_image_advisory_change.py
tests/test_lightblue.py
tests/test_pulp.py

Add configurable timeout to requests to avoid FM from hanging.

Add timeouts to requests in Freshmaker

---

freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
freshmaker/kojiservice.py
freshmaker/lightblue.py
freshmaker/models.py
freshmaker/odcsclient.py
tests/handlers/koji/test_rebuild_images_on_async_manual_build.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
tests/test_lightblue.py
tests/test_models.py

When an original image was built by freshmaker, there could be some odcs
composes added by freshmaker in build task, so if there is an image was
rebuilt by freshmaker for several times, the latest original image could
have some duplicated odcs composes in build task. For example:
1. image-2.1 was built and it has compose 101.
2. image-2-1 was rebuilt by freshmaker, new compose 102 added, new
NVR is image-2-1.0001, composes 101 and 102 are enabled in build
task.
3. image-2-1.0001 was rebuilt by freshmaker again, new compose 103
added, new NVR is image-2-1.0002, its build task has composes:
101, 102 and 103.
Then if freshmaker needs to rebuild image-2-1.0002, it will submit the
build task with composes: 101, 102 and 103. After 4694dda, freshmaker
doesn't add new composes which already …

Remove odcs composes added by freshmaker in original image

---

freshmaker/pyxis.py
tests/test_pyxis.py

A bundle can exists in multiple index images, get_latest_bundles should
return unique bundles, otherwise the botas handler can rebuild a bundle
for multiple times.
JIRA: CWFHEALTH-695

Fix get_latest_bundles to return unique bundles

---

freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
freshmaker/lightblue.py
freshmaker/models.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
tests/test_lightblue.py
tests/test_models.py

When manual rebuild is triggered for an advisory, freshmaker rebuilds
all affected images by default, there are two ways to change this
default behavior:
1. Specify the "container_images" in manual requests
2. Use "freshmaker_event_id" in manual requests, then the rebuilt
images in specified freshmaker event will be skipped.
However, when there are many events created for an advisory due to
some reasons, it's hard to skip rebuilt images in old events. In this
change, freshmaker is changed to skip rebuilt images in events
triggered by the same advisory by default. This behavior can be
changed by using `{"skip_rebuilt": false}` in metadata of manual
rebuild requests, for example:
curl -X POST -d '{"errata_id": 123, "metadata": {"skip_rebuilt": false}}' <url>
JIRA: CWFHEALTH-687

Skip rebuilt images in old events of advisory by default

---

freshmaker/lightblue.py

This quickfix affects error when connection to LightBlue is closed
during the request for some reason. Now request will be repeated
JIRA: CWFHEALTH-716

Retry LightBlue query when searching for images

---

freshmaker/events.py

It was changed by accident in ac0663c6 (in parse_post_data of
parsers/internal/manual_rebuild.py), set it in event directly
is better.

Fix manual value of ManualRebuildWithAdvisoryEvent events

---

requirements.txt

alembic >= 1.7 is not compatible with the migrations, this fixes
the mypy test failure:
freshmaker/migrations/env.py:9: error: Module has no attribute "config"; maybe "configure"?

Set alembic version to <1.7

---

fedmsg.d/freshmaker.py

1. disable fedora fedmsg endpoints by default
2. use 127.0.0.1 by default instead of host name 'fedmsg-relay'

Update default fedmsg config for local dev env

---

freshmaker/handlers/__init__.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/kojiservice.py
freshmaker/utils.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_handler.py
tests/test_kojiservice.py
tests/test_utils.py

If original bundle image has invalid OpenShift versions range, build
system still can rebuild it, but the rebuilt image will be invalid and
can not be shipped. Before submit the build task, freshmaker can check
the OpenShift versions range, in case it has an invalid value,
freshmaker can just move the build to FAILED state and not submit the
build task.
JIRA: CWFHEALTH-701

Check bundle image's OpenShift versions range

---

freshmaker/handlers/internal/update_db_on_odcs_compose_fail.py
freshmaker/handlers/koji/rebuild_images_on_odcs_compose_done.py
freshmaker/handlers/koji/rebuild_images_on_parent_image_build.py
tests/handlers/koji/test_rebuild_images_on_parent_image_build.py
tests/test_consumer.py
tests/test_monitor.py

Don't run the handlers for messages of unrelated odcs composes or brew tasks
(CWFHEALTH-706)

Don't run the handlers for unrelated messages

---

freshmaker/handlers/koji/rebuild_images_on_parent_image_build.py
tests/handlers/koji/test_rebuild_images_on_parent_image_build.py

When an RHSA has RPMs for a module stream, Freshmaker tries to
rebuild different versions of the image (example ruby-25, ruby-26,
ruby27), this is as expected because Freshmaker can not handle module
streams so it just rebuilds all images, and marks the unmatched
module streams as FAILED as a post build check. This seems not to
work when the build is manual. This change is making sure that it
works also for manual builds.
Signed-off-by: Giulia Naponiello <gnaponie@redhat.com>

Mark as FAILED images with unmatched module stream

---

freshmaker/events.py
freshmaker/handlers/__init__.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/kojiservice.py
freshmaker/models.py
freshmaker/parsers/internal/manual_rebuild.py
freshmaker/pyxis.py
freshmaker/utils.py
freshmaker/views.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py
tests/test_views.py

The main changes are:
1. While rebuilding unreleased bundles, freshmaker tries to get
bundle data from Pyxis, but actually Pyxis doesn't have bundle
data for unreleased bundles, this is fixed to use brew to get
bundle data.
2. Instead of getting all latest bundles first and check one by one,
use related image digest to get impacted bundles.
3. The manual case and auto case were handled differently, now they
are handled with same workflow.
4. Manual rebuild request is refactored to only use advisory to find
and construct the updated CSV data. "bundle_images" in request is
not used anymore.
JIRA: CWFHEALTH-914

Refactor the bundle rebuild handler

---

freshmaker/handlers/botas/botas_shipped_advisory.py
tests/handlers/botas/test_botas_shipped_advisory.py

When an unreleased bundle is rebuilt and the original bundle will not
be published, the rebuilt bundle is not going to substitute any existing
bundles, in this case, freshmaker should not add the olm.substitutesFor
annotation in rebuilt bundle.
JIRA: CWFHEALTH-1006

Support rebuilding bundle without olm.substitutesFor annotation

---

Dockerfile

Updating the Docker image to use Fedora 34. Once merged in Dev, will run the Ansible tower job and see if there are any issues.

Update the Freshmaker Docker Image to Fedora 34

---

freshmaker/kojiservice.py
tests/test_kojiservice.py

Besides of ".clusterserviceversion.yaml", CSV file can also endswith
".csv.yaml", so freshmaker should check both the suffixes.

CSV file can endswith ".csv.yaml"

---

freshmaker/config.py
freshmaker/errata.py
freshmaker/handlers/bob/rebuild_images_on_image_advisory_change.py
tests/handlers/bob/test_rebuild_images_on_image_advisory_change.py
tests/test_errata.py

JIRA: https://issues.redhat.com/browse/CWFHEALTH-859
**Update Bob message handler to avoid usage of Docker-Pulp**
- updated `get_docker_repo_tags` to parse external repo names from ET response
old response returned:  **{'foo-container-1-1': {'foo-526': ['5.26', 'latest']}}**
new response returns: **{'foo-526': ['5.26', 'latest']}**
- updated `rebuild_images_depending_on_advisory` to use updated `get_docker_repo_tags` and removed usage of Docker-pulp
- Removed docker pulp credentials from `config.py` and removed all instances of docker pulp usage from unit tests.

Update bob msg handler

---

freshmaker/pyxis.py
tests/test_pyxis.py

Change get_images_by_nvr to make it support passing
include_fields param.
Add an api to get the image's metadata and use these
metadata with auto_rebuild_tags api to check if this
image can be rebuilt or not.
JIRA: RHELWF-3779

Add methods to check if an image can be rebuilt

---

.github/workflows/docs.yml

Uses Fedora image and packages from "yum-packages-devel.txt" to build
the docs.
Allows building docs in pull requests, but deployment only on merge to
master.
JIRA: RHELWF-5244

CI: Fix building documentation

---

freshmaker/lightblue.py

This change is in regards to the comment mentioned from https://github.com/redhat-exd-rebuilds/freshmaker/pull/122
**tl;dr**:
It'd be simpler and more efficient to change this:
``` 
return all(
[self.name == other.name and self.version == other.version and self.repos == other.repos]
)
```
to
```
return self.name == other.name and self.version == other.version and self.repos == other.repos
```
because as of now, we are creating a list with a single boolean value and then calling the all function against it.

Change ImageGroup methods to be more efficient

---

freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/pyxis.py
tests/test_pyxis.py

Freshmaker find bundles by the manifest schema2 digest, but this
digest values are different for arches, seems bundle_path_digest
is the one from x86_64 image, but not sure about this, so the 
safest way is querying with digests from all available arches.

Find bundles by digests from all available arches

---

freshmaker/handlers/botas/botas_shipped_advisory.py

Bundles specified explicitly in manual rebuild request can include
unpublished images, freshmaker should not check the auto rebuild
tags for such bundles.

Don't check auto rebuild tags for bundles specified in manual rebuild

---

freshmaker/views.py
tests/test_views.py

When authentication is disabled, flask global namespace object `g`
doesn't have `g.user`.

Fix errors from views when authentication is disabled

---

requirements.in
requirements.txt

Flask-Migrate removed the support for Flask-Script since version 3,
which still be used by Freshmaker.

Use Flask-Migrate<3

---

freshmaker/events.py

Fixes storing freshmaker_event_id argument in DB.

Fix ignored argument in ManualRebuildWithAdvisoryEvent

---

freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/pyxis.py
tests/handlers/botas/test_botas_shipped_advisory.py
tests/test_pyxis.py

CWFHEALTH-908: "Ensure Freshmaker ignores hotfix images and does not try to rebuild them, or use them to trigger other rebuilds."

Make Freshmaker ignore operator hotfix images

---

freshmaker/lightblue.py
tests/test_lightblue.py

Operator/operand images can be hotfix images, which should be excluded from freshmaker's rebuild list (freshmaker excludes hotfix bundle images in CWFHEALTH-908). Operator/operand hotfix images can also be identified by "com.redhat.hotfix" label.

Exclude hotfix operator/operand images from rebuild list

---

freshmaker/errata.py
freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py
tests/test_errata.py

As discussed in the doc:
https://docs.google.com/document/d/1SR0Rh6ynZc-09Um91VGn7rZ33IS-x4KwbJsT-9m5HFk/edit#bookmark=id.d0h5hmxobp81
The type of advisory for the Flatpak application module is RHBA,
so we should use API advisory/{id}/builds.json to get the
build NVRs instead of API erratum/{id}/builds_by_cve
JIRA: RHELWF-6103

Change Errata API to get attached builds NVRs

---

freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py

The original idea is to create several small composes
so that they can be reused in different images, but as
metioned in RHELWF-5880, "Creating multiple ODCS composes
risks ODCS pulling in module builds that we don't want
through module dependency resolution.". So the fix is
just replace the compose old version module with new one.
JIRA: RHELWF-5880

Fix the issue to create multiple composes

---

freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py

As the flatpak application advisory is not
restricted to CVE related, we need to use new
API to get build rpm nvrs.

Add new method to get build rpm nvrs

---

freshmaker/errata.py

Errata made some changes to the xml-rpc APIs (RHELWF-7275), cause
mutual authentication to the xml-rpc endpoints doesn't work now.

Access Errata legacy HTTP APIs with optional mutual authentication

---

freshmaker/pyxis_gql.py
tests/test_pyxis_gql.py

New API get_repository_by_registry_path to get container repository by
registry path.

pyxis_gql: add new API get_repository_by_registry_path

---

freshmaker/config.py
tests/test_config.py

Add an option in Freshmaker to switch between using LightBlue and Pyxis GraphQL; Jira: CWFHEALTH-1246

Add a new option to get image metadata from LightBlue or Pyxis

---

requirements.txt

Fixes `/usr/bin/ld: cannot find -lldap_r` error when compiling python-ldap on Fedora 36.
The single dependency was updated manually in the generated requirements.txt file.

Fix failure building python-ldap

---

freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py

When using name:stream:version to create compose,
all contexts with the same name:stream:version will be returned in the result from MBS which is unexpected.
JIRA: RHELWF-7942

Make compose with name:stream:version:context

---

docs/configuration.rst
freshmaker/config.py
freshmaker/handlers/koji/rebuild_flatpak_application_on_module_ready.py
freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
freshmaker/lightblue.py
freshmaker/pyxis_gql.py
requirements.in
requirements.txt
test-requirements.txt
tests/conftest.py
tests/test_lightblue.py
tests/test_pyxis_gql.py
tox.ini
yum-packages.txt

The LightBlue class is updated to use Pyxis GraphQL APIs to find
container repositories and images, this is just a partial change so
there are still a lot of variables, functions in this class have not
been changed accordingly.
JIRA: CWFHEALTH-1708
JIRA: CWFHEALTH-1709
JIRA: CWFHEALTH-1710

Use Pyxis GraphQL APIs to find repositories and images

---

freshmaker/utils.py
tests/test_pyxis.py

Product pages APIs now requires trailing slash in urls, otherwise the APIs return empty results unless we follow the redirects.
```
$ curl https://<product-pages-url>/pp/api/v1/releases/openshift-4.10/schedule-tasks
<nothing>
$ curl https://<product-pages-url>/pp/api/v1/releases/openshift-4.10/schedule-tasks/
<result as expected>
$ curl -L https://<product-pages-url>/pp/api/v1/releases/openshift-4.10/schedule-tasks
<result as expected>
```

Fix product pages API url

---

freshmaker/utils.py
tests/test_pyxis.py

A product version can exist in product pages but doesn't have the GA date, freshmaker should also handle this case.

Fix get product version which doesn't have a GA date

---

freshmaker/config.py
freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py

As described in RHELWF-5866, making compose failed when including hidden content_set, probably the reason is ODCS thinks it is unpublished content set.
JIRA: RHELWF-5866

Exclude hidden content_set

---

.gitignore
freshmaker/container.py
freshmaker/pyxis_gql.py
tests/test_container.py
tests/test_pyxis_gql.py

(This Pull Requests continues #201.)
Pyxis supports authentication through kerberos. This method is preffered over SSL certificates because we won't need to renew our certificates periodically anymore.
This contribution implements kerberos authentication to the pyxis-gql.py module through the requests-kerberos library.
The Jira card associated with this contribution is https://issues.redhat.com/browse/CWFHEALTH-1762
I ran all the unit tests successfully. I also made manual e2e tests to make sure all queries were working properly. I used my personal kerberos credentials and send the requests to the dev pyxis gql endpoint.
I called all methods of the PyxisGQL class except for query, _get_repo_projection and _get_image_projection, which are called by the other methods. I ran the other …

Pyxis kerberos (squashed)

---

freshmaker/container.py
freshmaker/image.py
freshmaker/image_verifier.py
freshmaker/pyxis_gql.py
tests/test_container.py
tests/test_pyxis_gql.py

When use kerberos to authenticate to Pyxis, Pyxis doesn't return rpm_manifrest edges for image query APIs (JIRA: ISV-1957), so switch back to certificate authentication. The implementation of the certificate authentication has some changes, so instead of reverting f5ad1c2, this new commit is added.

Use certificate to authenticate to Pyxis

---

freshmaker/image.py
freshmaker/pyxis_gql.py

1. When find images by name and version to get published images, should query for published images only.
2. Update Pyxis result page size to our default value

Fix get published fixed image

---

Dockerfile
conf/config.py
freshmaker/views.py
requirements.txt

The fedora version that FM is using (f35) reached its end of life. Therefore, we need to update it.
I'm editing the old PR text and adding a few remarks. I'll mark them with "**[<ins>new</ins>]**".
List of changes:
- update package jsonformatter
- register api's v1 and v2 with different names in `view.py`
- gql installation through pip during the build process; I believe it is not available through dnf
- type hint in line 208 of `conf/config.py` (it was failing a flake8 check)
Please let me know if any of these are actually unnecessary!
Things that I managed to do:
- I ran unit tests (and tox) locally, all good!
- **[<ins>new</ins>]**  I built the image and deployed it to the dev environment! I also adapted and ran the "dry_run" script and got a good return:
```json
{
"builds":[], …
```

feat: bump fedora version

---

.github/workflows/docs.yml
.github/workflows/tests.yml
Jenkinsfile
README.md
docs/db.rst
freshmaker/views.py
requirements.txt
tox.ini

In order to eradicate problematic language, we should rename our default branch to "main" instead of "master".
This PR changes the occurrences of "master" to "main" in a few files, so we can rename the default branch of our repo accordingly. These occurrences are mainly paths and action triggers.
Some occurrences are not relative to our repo (for what I figured), and were left as-is.
I would like to ask you, reviewers, the following:
- do you think something is missing?
- do you think some change is unnecessary?
Please let me know your thoughts!
**[EDIT]** I deleted the 'main' branch I previously created in the Freshmaker upstream repo. I'll follow Qixiang's suggestion and just rename the 'master' branch once everything is ready. The steps will be simpler in this approach:
- merge the …

feat: rename default branch do "main"

---

.github/workflows/docs.yml

The docs buliding action was failing, apparently because some dependencies were not available in the 'fedora' repo, to which the tox action step was restricted. It would fail because of unprovided dependencies.
Removing the restriction of using only the 'fedora' repo in the tox step solved this problem.
- I ran the docs job with act locally, it worked fine!
- I also ran the workflow in my fork. Both the doc building and the doc deployment worked fine there, as well!
- you can see the job status in the action page: https://github.com/FernandesMF/freshmaker/actions/runs/4556545982/jobs/8037038631
- also you can see the deployed documentation in the 'gh-pages' branch: https://github.com/FernandesMF/freshmaker/tree/gh-pages
I wanted to check with you if this approach is fine.
I thought there …

fix(CI-docs): Allow more dep. repos in tox step

---

docs/conf.py
freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/kojiservice.py
tests/handlers/botas/test_botas_shipped_advisory.py

When original image has `olm.substitutesFor` annotation, in most cases it was added by Freshmaker with the `operator_csv_modifications_url` in build task parameters, it's not in any file from dist-git repo, when Freshmaker rebuild this image and don't add any new `olm.substitutesFor` annotation, the `olm.substitutesFor` annotation in original image will be lost, this is wrong.
JIRA: CWFHEALTH-2003

Keep olm.substitutesFor from original image

---

freshmaker/pyxis_gql.py

Fetching Pyxis GraphQL schema is time consuming, this can be a performance bottelneck when Freshmaker creates many PyxisGQL instances.

Cache Pyxis GraphQL schema

---

freshmaker/config.py
freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
freshmaker/pulp.py
tests/test_pulp.py

Pulp is deprecating user/password authentication, and switching to certificate-based auth instead.
This commit:
- implements the change in the authentication method in the pulp module
- updates unit tests for teh pulp module
- fixes a call in `freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py`
- substitutes the credential templates in `freshmaker/config.py`
JIRA: CWFHEALTH-2004
I have been able to test the access of our certificates to the Pulp API, and also the updated authentication method in the Pulp requests:
- I ran the curl command the Pulp team suggested in their documentation page and checked that the certificates (both dev and prod) are working fine
- I made a script and called the Pulp class and its post method (using the dev certificates), it also worked fine. …

Certificate-based authentication for Pulp

---

freshmaker/config.py
freshmaker/pyxis_gql.py
freshmaker/pyxis_gql_async.py

Introduced two config variables:
1. pyxis_default_page_size
2. pyxis_small_page_size
which can be specified as page_size in Pyxis requests.
Some Pyxis queries are resource consuming and Pyxis may not be able to
handle them in a time manner, use a low number of page_size can help in
such cases.
The resource consuming queries usually have complex search criteria and
Pyxis has to check a lot of entities in backend, or the search hit a
large number of entities in database which is unpredictable at client
side, in such cases, use the pyxis_small_pyxis_size can probably help
Pyxis to handle the request.
The find_images_by_installed_rpms API is one of such queries, so we use
the configured small page_size in this API.

Make page_size in Pyxis requests configurable

---

freshmaker/handlers/botas/botas_shipped_advisory.py
freshmaker/views.py
tests/handlers/botas/test_botas_shipped_advisory.py

- added a new attribute `manual_image_remap` to the `ManualBundleRebuildEvent` class
- implemented logic to make the remapping of nvrs, following that new attribute, in `HandleBotasAdvisory`
- implemented logic to conditionally include the remapping information to the event in `FreshmakerManualRebuildParser`

NVR explicit replacing in manual bundle rebuilds

---

freshmaker/image.py

Pyxis may contains some invalid image metadata, for example, an image missing rpm_manifest, when such image data is returned by Pyxis, Freshmaker rebuild event will raise an exception, but it's hard to figure out which image caused the exception, logging the image NVR can help us on finding out the problematic image and fix it in metadata.
JIRA: CWFHEALTH-2104

Logging invalid image NVR for troubleshooting

---

conf/config.py
freshmaker/__init__.py
freshmaker/config.py
freshmaker/logger.py

There are a few issues with the current logging, let's enhance it!
The cause was that in the `logger.py` module, the log level was being set from an environment variable called "DEBUG" that was not being set in the deployment.
Since there is a setting for the config level in the configuration file, I changed it to get the setting from there.
After doing that, I made a quick deployment to dev and I saw some debug-level lines in the logs.
The solution I found was to include change the gql module logging level in the configs. That change is in the internal repo.
The cause behind this issue was that there were two handlers to the console: one in the root logger, which was being configured with a stream handler to `stderr` by the `basicConfig()` commands, and the second in the child …

Improve logging

---

freshmaker/handlers/__init__.py
freshmaker/handlers/internal/update_db_on_odcs_compose_fail.py
freshmaker/handlers/koji/rebuild_images_on_parent_image_build.py

When the last build in event failed due to ODCS compose error, the build state will be changed to FAILED, but Freshmaker doesn't update the event to COMPLETE state.
JIRA: CWFHEALTH-2162

Update event state when the last build failed due to ODCS compose error

---

.github/workflows/docs.yml

The "tox-github-action" has been changed to use `main` branch as default branch and `master` branch is not available now.

Fix doc build job

---

freshmaker/config.py
freshmaker/handlers/botas/botas_shipped_advisory.py
tests/handlers/botas/test_botas_shipped_advisory.py

Sometimes, it can happen that a bundle loses track of the latest image of an operator/operand, in case they are both rebuilt but the bundle rebuild fails to ship. In this case, new rebuilds of those operator/operand will no longer trigger a rebuild of the bundle.
For example, imagine we have a bundle 'bundle-2-234' and a related image 'foo-1-123', and the following happens:
1. the image gets rebuilt to 'foo-1-123.234' and the bundle also happens a rebuild triggered, but it fails to ship
2. then the image gets rebuild again to 'foo-123-456'
3. this new rebuild of 'foo-1-123' will not trigger a rebuild of the        bundle, as it is not related to 'foo-123-456'
The manual overriding feature can be used to circumvent this issue, but it is better if we can make an automatic solution.
This …

Automatic rebuild of old operators/operands images

---

freshmaker/handlers/__init__.py
freshmaker/types.py
tests/test_image.py

A new version of flake8 was released, and it complains about type comparison in some places in our code:
> E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`"
This commit fixes these comparisons according to flake8 suggestion.
For completeness, here are the errors that popped up prior to this fix:
``` python
./freshmaker/handlers/__init__.py:241:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
./freshmaker/handlers/__init__.py:245:14: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
./freshmaker/types.py:51:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()` …
```

Fix errors pointed by new flake8 version

---

freshmaker/pyxis_gql.py
yum-packages.txt

The gql RequestsHTTPTransport has retries enabled, but it doesn't retry when Pyxis requests timeout, for some requests, Pyxis may take more time than its gateway timeout value to process them, and it will return the result with error in response. In such cases, retrying may work.
This is a workaround for JIRA: CLOUDWF-9342

Retry Pyxis requests on timeout

---

freshmaker/pulp.py
tests/test_pulp.py

A while ago, Pulp authentication was refactored, and the pulp-docker configurations became unused
(https://github.com/redhat-exd-rebuilds/freshmaker/commit/1c87c5220c718cc221cdae2396bf5cb57a06beef).
This commit removes an unused function in the pulp module, and the related tests.
JIRA: CWFHEALTH-2084

Remove unused pulp-docker configs and function

---

freshmaker/image.py

Freshmaker has a Pyxis request which is used to find images that have particular content sets enabled and have particular rpms installed, this request is time consuming and it's hard to tell how complex this request will be because the query and filter is performed at Pyxis backend, and with the number of images grow in underlying database, same request can take more time to finish.
We're seeing request timeout with 100 repositories in a single request, adjust the number to 50 to workaround the issue.

Send Pyxis request with less repositories

---

freshmaker/image.py
freshmaker/pyxis_gql.py
freshmaker/pyxis_gql_async.py

1. Include `brew.package` in image metadata returned by Pyxis, it's used by async build feature.
2. In async build handler, PyxisAPI instance is used with its APIs, but while resolving an image, the resolve methods accepts a PyxisGQL instance, so async build fails with `find_images_by_nvr` method not found, just wrap the API in PyxisAPI as a workaround.

Fix async build

---

freshmaker/pyxis_gql.py
tests/test_pyxis_gql.py
tox.ini

1. Fix retry for Pyxis request timeout
In 31cc4ca, we added retry mechanism when Pyxis request timeout, however
we detect the Pyxis request timeout by:
if "Pyxis API was unable to fetch data from MongoDB in time" in error
`error` is actually a dict, not a string, so this doesn't work.
2. Disable flake8 W503
W503 warning in Flake8 goes against PEP 8 recommendation, disable it to
make it compatible with black.
W503 line break before binary operator
https://peps.python.org/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

Fix pyxis timeout retry

---

freshmaker/pyxis_gql.py

Caching should not be enabled for some find images APIs, because the result can change at any time, if we have caching for such APIs, images just be released may not be returned by these APIs which can cause wrong result of images to be rebuilt.
These APIs are from `pyxis_gql` module:
1. find_images_by_installed_rpms
2. find_images_by_names
3. find_images_by_name_version
4. find_images_by_repository
Caching for other find images APIs is fine:
1. find_images_by_nvr
2. find_images_by_nvrs

Remove caching for some find images APIs

---

freshmaker/pyxis_gql.py
freshmaker/pyxis_gql_async.py

The requests in find_images_by_installed_rpms API are very inefficient, including the `total` field can make the query performance much worse.

Exclude `total` field from Pyxis request's projection

---

freshmaker/parsers/errata/state_change.py
tests/handlers/koji/test_rebuild_flatpak_application_on_module_ready.py

Before b76bd0a, freshmaker appends the advisory name to message id when event is triggered by rpm advisory shipped message, it's still useful for us to know whether an event was triggered by E2E testing advisories (which type is RHBA) without opening Errata tool, so adding it back.

Append advisory name to message id

---

.git-blame-ignore-revs

Github changed the commit hash of the large reformatting rev after merging 🥲 
I'm making this quick patch to fix that.

Update large rev hash in .git-blame-ignore-revs

---

conf/config.py
freshmaker/container.py
tests/test_container.py

Changes to the Container class:
1. Change Container class to normal class
The class originally implemented using dataclass didn't have many of the advantages of dataclass, but rather made creating instances more difficult to understand. The reason is a container can have multi-arch images, most attributions doesn't have one-to-one mapping with a single image data.
2. Use class method `create_from_images` to create Container instances
It was implemented with instantiating it first then load per-arch data with `load` which is confusing.
3. Remove `resolve_published`
Just check if a container is published by checking that in all deliver repositories.
JIRA: CWFHEALTH-2313

Refactor the Container class

---

freshmaker/parsers/errata/state_change.py

Check event state before issuing ErrataRPMAdvisoryShippedEvent
In a previous refactoring, we simplified how Freshmaker generates ErrataRPMAdvisoryShippedEvent's.
However, we forgot to check the state of the incoming errata events, and FM is currently issuing
ErrataRPMAdvisoryShippedEvent for all Errata events, even those which are not shipping events.
This commits places a check to ensure that ErrataRPMAdvisoryShippedEvent will only be issued
for the correct kind of Errata events.
I made a deployment to the dev environment, using the initial messages. I didn't see any errors for the initial messages nor the other messages after two days.
JIRA: CWFHEALTH-2351

only generate ErrataRPMAdvisoryShippedEvent for 'shipped live' events

---

Dockerfile
yum-packages.txt

Quay is pointing security issues in Freshmaker due to outdated packages. We currently install the latest package versions available for the fedora version in use. Therefore, to fix the issues, we needed to upgrade the fedora version.
Freshmaker was using fedora 37, and after upgrading to fedora 38, a number of issues were resolved. The rest of the issues that are marked as fixable are due to fedora 39 packages, but it won't become GA before a few weeks from now.
With f38, the total number of issues decreased from 21 to 13, and the number of fixable issues fell from 18 to 10. The issues with the packages `werkzeug`, `mako` and `mod-wsgi` were resolved.
The package `python3-krbcontext` is only available for f37. I removed it from `yum-packages.txt` and it didn't seem to impact freshmaker.
I …

Fix security issues pointed by Quay

---

conf/config.py
freshmaker/errata.py
freshmaker/events.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
tests/test_errata.py
tests/test_handler.py

Freshmaker currently supports major incidents only in Bugzilla, but some products file those trackers in JIRA.
This commit implements the logic to check if a tracker in JIRA corresponds to a major incident, by using the Errata API.
The changes are the following:
- new function `Errata.has_jira_major_incidents` to check if a tracker in JIRA refers to a major incident
- new function `Errata._get_jira_issues` to fetch jira trackers
- inclusion of the new check in `ErrataAdvisory.from_advisory_id`, to add support to the JIRA trackers
- renaming of 'hightouch' to 'major_incident' in several points across the codebase, to reflect the new logic
- a new unit test for `Errata.has_jira_major_incidents`, with all the expected cases that it should handle
- adjustment to tests and configuration …

Enable support for 'major incidents' in JIRA

---

freshmaker/image.py
freshmaker/pyxis_gql.py
freshmaker/pyxis_gql_async.py
tests/test_image.py
tests/test_pyxis_gql.py
tests/test_pyxis_gql_async.py

Due to regressing content, it might happen, in rare conditions, that the parent image of the image we are rebuilding after a CVE fix doesn't include all the latest fixes.
Example: we have 3 images:
NVR | CVE fixes
foo-1-125: fix-a, fix-b
foo-1-124: fix-a, fix-c
bar-2-220: fix-a, fix-b
foo is parent of bar. Before this change, Freshmaker would ask Pyxis if there's already a parent image fixing fix-c, and it would return foo-1-124, so that Freshmaker can use that as parent of bar. But that image is missing fix-b!
To prevent this issue, from now on, Freshmaker ask to Pyxis only the latest image.
Tests are not updated, since the current tests should cover the case.

Replace the parent image only with the latest one

---

conf/config.py
freshmaker/config.py

To facilitate configurable predefined image repositories for moderate/low RHSA rebuilds, Freshmaker will have the capability to retrieve predefined image repositories from a remote URL. For this purpose we are introducing the configuration vaiable COMPLIANCE_PRIORITY_REPOSITORIES_REMOTE_FILE.
ref: CWFHEALTH-2491

Introduce config var COMPLIANCE_PRIORITY_REPOSITORIES_REMOTE_FILE

---

freshmaker/errata.py
freshmaker/events.py
tests/test_errata.py

Freshmaker has a preconfigured allowlist that currently only permits advisories of critical and important severity to trigger image rebuilds. There is a requirement to address moderate and low CVEs, though.
To address the new requirement, this allowlist needs to be expanded to include moderate and low security impact RHSAs. However, not all moderate/low CVE fix RHSA advisories should trigger Freshmaker rebuilds. Freshmaker should only react to moderate/low CVE fix advisories when they have any security compliance bugs/issues attached.
This commit implements the check for compliance priority issues and bugs.
The changes are the following:
- new parameter `is_compliance_priority` in the `ErrataAdvisory` class
- logic to fetch 'compliance-priority+' flag in bugs in …

 Identify RHSAs with compliance priority bugs/issues

---

freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
freshmaker/image.py
freshmaker/pyxis_gql.py
freshmaker/pyxis_gql_async.py
freshmaker/utils.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
tests/test_utils.py

When rebuilding for lower-severity advisories, we do not want to check the images in  all repositories in Pyxis. Instead, we want to restrain our search to a (dynamic) short list of predefined repos, stored in a remote yaml file, as this is more efficient.
This commit implements this functionality through the following changes:
- new logic in `RebuildImagesOnRPMAdvisoryChange._find_images_to_rebuild` to fetch external repos from the remote yaml file, in case advisory priority is `moderate`
- new functions `RebuildImagesOnRPMAdvisoryChange._lookup_external_repos` and `utils.py/load_remote_yaml` to fetch the content of the remote yaml file
- new parameters `repositories` and `repositories` in the methods `PyxisAPI.find_images_with_packages_from_content_set`, …

Enable use of external repos in lower-severity rebuilds

---

freshmaker/odcsclient.py

With the `use_only_compatible_arch` flag, the ODCS produced repofile will use a $basearch variable in the repourl, then build task for an arch won't have irrelevant arch repos enabled. This can help especially for base image builds, when irrelevant arch repos are enabled, it can cause the build task to be slower and occupy more memory, and can cause unexpected issues like RHELBLD-14336 where base images can not be built due to x86_64 appstream repo is enabled for non-x86_64 build tasks.
JIRA:CWFHEALTH-2746

Request ODCS pulp composes with `use_only_compatible_arch` flag

---

freshmaker/pyxis_gql.py
tests/test_pyxis_gql.py

It doesn't handle the case when Pyxis returns empty images.

Fix find_latest_images_by_name_version

---

freshmaker/errata.py
tests/test_errata.py

Errata has changed its builds-by-cve API to return rpms in string list to list of dicts, old format example:
"x86_64": [
"krb5-libs-1.8.2-3.el6_0.7.i686.rpm",
"krb5-libs-1.8.2-3.el6_0.7.x86_64.rpm"
]
new format:
"x86_64": [
{
"filename": "krb5-libs-1.8.2-3.el6_0.7.i686.rpm",
"is_signed": true
},
{
"filename": "krb5-libs-1.8.2-3.el6_0.7.x86_64.rpm",
"is_signed": true
}
]
This commit updates Freshmaker to accommodate the changes in the result format introduced by the latest ET API.
JIRA: CLOUDWF-10046

Fix for ET's builds-by-cve API new result format

---

freshmaker/errata.py
freshmaker/events.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
tests/test_errata.py

This introduces the release_name attribute to the ErrataAdvisory class, it enables filtering events by advisory release name.
JIRA: CWFHEALTH-3043

Add release name to ErrataAdvisory for filtering

---

freshmaker/handlers/koji/rebuild_images_on_rpm_advisory_change.py
freshmaker/image.py
tests/handlers/koji/test_rebuild_images_on_rpm_advisory_change.py
tests/test_image.py

Extend the image metadata available to allowlist/blocklist functionality, adding the published repository name on top of the existing NVR information.
The published repo name includes the registry namespace, which lets us fine-tune rebuild criteria for a group of images (products, releases, other subdivisions) without needing to maintain full lists of images in Freshmaker configuration.
JIRA: CWFHEALTH-3013

Allow filtering out images by published repository name

---

freshmaker/config.py
freshmaker/image.py
requirements.txt
tests/test_image.py

When a base image included in the rebuild list as a dependency is not the latest published release, replace it with the latest one. This ensures that outdated base images, which might reference non-existent resources, do not cause build failures. By using the latest base images, we can ensure successful image builds.
JIRA: CWFHEALTH-3258

Replace outdated base images with the latest ones

---

freshmaker/image.py
tests/test_image.py

Images built and released by Konflux lack Brew metadata. Freshmaker will encounter problems, because it currently expects this data.
This commit makes Freshmaker ignore those images. This is done in `images.PyxisAPI.find_images_with_included_rpms`, right after querying pyxis, by checking the brew nvr field.

Ignore images with missing brew nvr data

---

freshmaker/errata.py

Due to the implementation of the allow list and block list, freshmaker is actually checking all advisories with all state changes. When freshmaker lacks permissions to access certain Jira issues, it continuously retries these checks, causing significant performance degradation.
This change removes retry attempts for Jira permission errors, as these retries would never succeed. This workaround prevents unnecessary delays in processing advisory state change events.

Skip retries for Jira errors

---

.github/workflows/docs.yml
.github/workflows/tests.yml

The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025.

Update ubuntu runner image

---

freshmaker/utils.py

Add error handling for JSONDecodeError when parsing Product Pages API response to prevent crashes when the API returns non-JSON content.

Fix JSON parsing error in get_ocp_release_date
